module.exports = {
    ADD_ITEM: 'ADD_ITEM',
    SELECT_ITEM: 'SELECT_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    TOGGLE_ITEM: 'TOGGLE_ITEM',
    SET_BLOCKED: 'SET_BLOCKED',
    ADD_BULK: 'ADD_BULK',
    ADD_BULK_BLOCKED: 'ADD_BULK_BLOCKED'
};
